### ISSUE TITLE
난이도 조정

### ISSUE THREAD

**Issue by Lumia1108** [Astro36/word-chain-bot#1]
난이도를 낮춰야 한다 생각합니다.
<img src="https://www.dropbox.com/s/2w34n6qcgrua6cx/Screenshot_20170712-200317.png?dl=1"></img>
렌으로 시작하는 단어를 대부분의 사람들이 모릅니다.
예를 들어 렌닌은 의학용어라서 많은 사람들이 알고있지 않은 단어라고 생각합니다.

**Comment by Astro36** [comment]
`렌`으로 시작하는 `렌더링`, `렌즈`, `렌츠`, `렌치`, `렌트겐`, 등을 포함하여 단어는 총 36개가 있습니다.
그 밖의 스택단어는 매너 규칙(Rule.MANNER)을 적용하세요.

**Comment by Lumia1108** [comment]
하지만 그외에도 어려운 단어가 있습니다(사진의 난이도는 Easy입니다.)
<img src="https://www.dropbox.com/s/friq9kczxoyjxvs/Screenshot_20170712-201419.png?dl=1"></img>
'째'로 시작하는 단어 역시 대부분의 사람들이 모릅니다.

**Comment by Astro36** [comment]
`째릿째릿`, `째릿`, `째깍`, `째릉` 등을 포함하여 89개의 단어가 존재합니다.
난이도 수정은 고려해보겠습니다.
